DROP TABLE COMPATIBILITY_RESULTS CASCADE CONSTRAINTS;

CREATE TABLE COMPATIBILITY_RESULTS (
    Result_ID NUMBER PRIMARY KEY,
    Build_ID NUMBER NOT NULL,
    Game_ID NUMBER NOT NULL,
    Status VARCHAR2(20) NOT NULL,
    Check_Date DATE DEFAULT SYSDATE,
    CONSTRAINT chk_status CHECK (Status IN ('FAIL', 'MINIMUM', 'RECOMMENDED', 'ULTRA')),
    CONSTRAINT fk_compat_build FOREIGN KEY (Build_ID) REFERENCES USER_PC_BUILDS(Build_ID) ON DELETE CASCADE,
    CONSTRAINT fk_compat_game FOREIGN KEY (Game_ID) REFERENCES GAMES(Game_ID) ON DELETE CASCADE
);

INSERT INTO COMPATIBILITY_RESULTS (Result_ID, Build_ID, Game_ID, Status) VALUES (1, 1, 1, 'ULTRA');
INSERT INTO COMPATIBILITY_RESULTS (Result_ID, Build_ID, Game_ID, Status) VALUES (2, 4, 1, 'FAIL');
INSERT INTO COMPATIBILITY_RESULTS (Result_ID, Build_ID, Game_ID, Status) VALUES (3, 3, 11, 'RECOMMENDED');
INSERT INTO COMPATIBILITY_RESULTS (Result_ID, Build_ID, Game_ID, Status) VALUES (4, 7, 26, 'MINIMUM');
INSERT INTO COMPATIBILITY_RESULTS (Result_ID, Build_ID, Game_ID, Status) VALUES (5, 5, 8, 'ULTRA');
INSERT INTO COMPATIBILITY_RESULTS (Result_ID, Build_ID, Game_ID, Status) VALUES (6, 6, 12, 'RECOMMENDED');
INSERT INTO COMPATIBILITY_RESULTS (Result_ID, Build_ID, Game_ID, Status) VALUES (7, 2, 48, 'RECOMMENDED');
INSERT INTO COMPATIBILITY_RESULTS (Result_ID, Build_ID, Game_ID, Status) VALUES (8, 9, 3, 'FAIL');
INSERT INTO COMPATIBILITY_RESULTS (Result_ID, Build_ID, Game_ID, Status) VALUES (9, 12, 28, 'ULTRA');
INSERT INTO COMPATIBILITY_RESULTS (Result_ID, Build_ID, Game_ID, Status) VALUES (10, 8, 24, 'RECOMMENDED');
INSERT INTO COMPATIBILITY_RESULTS (Result_ID, Build_ID, Game_ID, Status) VALUES (11, 1, 33, 'ULTRA');
INSERT INTO COMPATIBILITY_RESULTS (Result_ID, Build_ID, Game_ID, Status) VALUES (12, 6, 11, 'RECOMMENDED');
INSERT INTO COMPATIBILITY_RESULTS (Result_ID, Build_ID, Game_ID, Status) VALUES (13, 4, 48, 'MINIMUM');
INSERT INTO COMPATIBILITY_RESULTS (Result_ID, Build_ID, Game_ID, Status) VALUES (14, 11, 1, 'RECOMMENDED');
INSERT INTO COMPATIBILITY_RESULTS (Result_ID, Build_ID, Game_ID, Status) VALUES (15, 3, 8, 'MINIMUM');

COMMIT;

