DROP TABLE OPERATING_SYSTEMS CASCADE CONSTRAINTS;

CREATE TABLE OPERATING_SYSTEMS (
    OS_ID NUMBER PRIMARY KEY,
    OS_Name VARCHAR2(100) NOT NULL,
    Architecture VARCHAR2(20) NOT NULL,
    CONSTRAINT chk_architecture CHECK (Architecture IN ('32-bit', '64-bit'))
);

INSERT INTO OPERATING_SYSTEMS VALUES (1, 'Windows 10 Home', '64-bit');
INSERT INTO OPERATING_SYSTEMS VALUES (2, 'Windows 10 Pro', '64-bit');
INSERT INTO OPERATING_SYSTEMS VALUES (3, 'Windows 11 Home', '64-bit');
INSERT INTO OPERATING_SYSTEMS VALUES (4, 'Windows 11 Pro', '64-bit');
INSERT INTO OPERATING_SYSTEMS VALUES (5, 'Windows 7 Professional', '64-bit');
INSERT INTO OPERATING_SYSTEMS VALUES (6, 'Windows 7 Professional', '32-bit');
INSERT INTO OPERATING_SYSTEMS VALUES (7, 'Ubuntu 22.04 LTS', '64-bit');
INSERT INTO OPERATING_SYSTEMS VALUES (8, 'Ubuntu 24.04 LTS', '64-bit');
INSERT INTO OPERATING_SYSTEMS VALUES (9, 'SteamOS', '64-bit');

COMMIT;