DROP TABLE GAME_CATEGORIES CASCADE CONSTRAINTS;
CREATE TABLE GAME_CATEGORIES (
    Category_ID NUMBER PRIMARY KEY,
    Category_Name VARCHAR2(100) NOT NULL UNIQUE
);

INSERT INTO GAME_CATEGORIES VALUES (1, 'Action / Adventure');
INSERT INTO GAME_CATEGORIES VALUES (2, 'Competitive FPS / Esports');
INSERT INTO GAME_CATEGORIES VALUES (3, 'Open World / RPG');
INSERT INTO GAME_CATEGORIES VALUES (4, 'Racing / Simulation');
INSERT INTO GAME_CATEGORIES VALUES (5, 'Sports / Fighting');
INSERT INTO GAME_CATEGORIES VALUES (6, 'Strategy / MOBA');
INSERT INTO GAME_CATEGORIES VALUES (7, 'Survival / Horror');

COMMIT;