DROP TABLE RAM_CONFIGURATIONS CASCADE CONSTRAINTS;

CREATE TABLE RAM_CONFIGURATIONS (
    RAM_ID NUMBER PRIMARY KEY,
    Capacity_GB NUMBER NOT NULL,
    DDR_Generation VARCHAR2(10) NOT NULL,
    CONSTRAINT chk_ram_capacity CHECK (Capacity_GB > 0),
    CONSTRAINT chk_ddr_gen CHECK (DDR_Generation IN ('DDR3', 'DDR4', 'DDR5'))
);

INSERT INTO RAM_CONFIGURATIONS VALUES (1, 4, 'DDR3');
INSERT INTO RAM_CONFIGURATIONS VALUES (2, 8, 'DDR3');
INSERT INTO RAM_CONFIGURATIONS VALUES (3, 16, 'DDR3');
INSERT INTO RAM_CONFIGURATIONS VALUES (4, 32, 'DDR3');

INSERT INTO RAM_CONFIGURATIONS VALUES (5, 4, 'DDR4');
INSERT INTO RAM_CONFIGURATIONS VALUES (6, 8, 'DDR4');
INSERT INTO RAM_CONFIGURATIONS VALUES (7, 16, 'DDR4');
INSERT INTO RAM_CONFIGURATIONS VALUES (8, 32, 'DDR4');
INSERT INTO RAM_CONFIGURATIONS VALUES (9, 64, 'DDR4');
INSERT INTO RAM_CONFIGURATIONS VALUES (10, 128, 'DDR4');

INSERT INTO RAM_CONFIGURATIONS VALUES (11, 8, 'DDR5');
INSERT INTO RAM_CONFIGURATIONS VALUES (12, 16, 'DDR5');
INSERT INTO RAM_CONFIGURATIONS VALUES (13, 24, 'DDR5');
INSERT INTO RAM_CONFIGURATIONS VALUES (14, 32, 'DDR5');
INSERT INTO RAM_CONFIGURATIONS VALUES (15, 48, 'DDR5');
INSERT INTO RAM_CONFIGURATIONS VALUES (16, 64, 'DDR5');
INSERT INTO RAM_CONFIGURATIONS VALUES (17, 96, 'DDR5');
INSERT INTO RAM_CONFIGURATIONS VALUES (18, 128, 'DDR5');

COMMIT;